stages:
  process-data:
    cmd: matlab -noFigureWindows -batch "run('scripts/process_data.m');"
    deps:
      - scripts/process_data.m
      - data/raw
    outs:
      - data/processed:
          cache: false # Keep in Git since they will be small CSVs
  plot-data:
    cmd: matlab -noFigureWindows -batch "run('scripts/plot_figures.m');"
    deps:
      - scripts/plot_figures.m
      - data/raw
      - data/processed
    outs:
      - figures
